### ISSUE TITLE
v1 Tracker

### ISSUE THREAD

**Issue by stachu540** [stachu540/ALICE#1]
# Common

* [ ] Using only Kotlin JVM
* [ ] Deployment solutions using Github Actions
  * [ ] Nightly build - only `master` branch
  * [ ] Release build - only created tags and release

# API

* [ ] `Alice` interface
* [ ] `Engine` API
  * [ ] `Command` API
  * [ ] `Module` API
* [ ] `Storage` API
* [ ] `Config` API
* [ ] `WebComponent` API
  * [ ] Settings API - assignable for each Engine and Module
  * [ ] `TemplateEngine` API
* [ ] Documentation
* [ ] Events API

# Server

* [ ] Docker image
* [ ] Spring Boot
  * [ ] `BeanFactory` for each API's (except `WebCompenent`)
  * [ ] `WebComponent` proxy implementation
  * [ ] `TemplateEngine` proxy implementation
  * [ ] Arguments support
  * [ ] Events with filtering
  * [ ] Login Component (with permissions)

# Client (using Electron) [Kotlin JS]

* [ ] Login Panel
* [ ] Dashboard View (pulled from web)
* [ ] Event View (pulled from web)

# Module / Engine development

* [ ] Maven MOJO Plugin
* [ ] Gradle Plugin
* [ ] Plugin API
* [ ] Documentation

# Engine Samples

* [ ] Discord
* [ ] Twitch
* [ ] Facebook Gaming
* [ ] Youtube Gaming
